In [9]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Mall_Customers.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Genre                   200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [10]:
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [11]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [13]:
df.Age.mean()

np.float64(38.85)

In [14]:
df.Age.min()

18

In [16]:
df['Age'].max()

70

In [17]:
df.Age.std()

13.969007331558883

In [18]:
df.Age.mode()

0    32
Name: Age, dtype: int64

In [19]:
df.Genre.mode()

0    Female
Name: Genre, dtype: object

In [20]:
df.Age.median()

36.0

In [24]:
print(df.groupby(["Genre"]).mean())

        CustomerID        Age  Annual Income (k$)  Spending Score (1-100)
Genre
Female   97.562500  38.098214           59.250000               51.526786
Male    104.238636  39.806818           62.227273               48.511364

In [25]:
df.shape

(200, 5)

In [26]:
df.dtypes

CustomerID                 int64
Genre                     object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

In [28]:
summary=df.groupby('Genre')['Annual Income (k$)'].describe()
print(summary)

        count       mean        std   min    25%   50%    75%    max
Genre
Female  112.0  59.250000  26.011952  16.0  39.75  60.0  77.25  126.0
Male     88.0  62.227273  26.638373  15.0  45.50  62.5  78.00  137.0

In [29]:
summary=df.groupby('Genre')['Annual Income (k$)'].describe()
print(summary)

        count       mean        std   min    25%   50%    75%    max
Genre
Female  112.0  59.250000  26.011952  16.0  39.75  60.0  77.25  126.0
Male     88.0  62.227273  26.638373  15.0  45.50  62.5  78.00  137.0